[package]
name = "egui_transition_animation"
version = "0.1.7"
edition = "2024"
authors = ["FireFragment"]
description = "Easy animated transitions between multiple pages in egui"
repository = "https://github.com/FireFragment/egui_transition_animation"
license.workspace = true
keywords = ["egui", "animation", "transition", "ui", "gui"]
categories = ["gui"]

[dev-dependencies]
eframe = "0.33.0"
env_logger = "0.11.8"

[dependencies]
egui = "0.33.0"
